modLoader="javafml"
loaderVersion="[50,)"
license="MIT"
issueTrackerURL="https://github.com/PTOM76/legacy-itemmodels/issues"

[[mods]]
modId="legacyitemmodels"
version="${version}"
displayName="Legacy Itemmodels"
displayURL="https://curseforge.com/minecraft/mc-mods/legacy-itemmodels"
logoFile="icon.png"
authors="PitaQ"
description='''
The mod enables backward compatibility for your Minecraft data packs.
'''

[[dependencies.legacyitemmodels]]
modId="forge"
mandatory=true
versionRange="[50,)"
ordering="NONE"
side="BOTH"

[[dependencies.legacyitemmodels]]
modId="minecraft"
mandatory=true
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"
