modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/PTOM76/legacy-itemmodels/issues"

[[mods]]
modId="legacyitemmodels"
version="${version}"
displayName="Legacy Itemmodels"
displayURL="https://curseforge.com/minecraft/mc-mods/legacy-itemmodels"
logoFile="icon.png"
authors="PitaQ"
description='''
The mod enables backward compatibility for datapacks.
'''

[[dependencies.legacyitemmodels]]
   modId="neoforge"
   type = "required"
   versionRange="[21.0.40-beta,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.legacyitemmodels]]
   modId="minecraft"
   type = "required"
   versionRange="[1.21,)"
   ordering="NONE"
   side="BOTH"

[[mixins]]
config = "legacyitemmodels-common.mixins.json"
